"""removed bio column from user table

Revision ID: 4a68725c09dc
Revises: 37ddb4c43df1
Create Date: 2023-02-08 15:51:53.315492

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '4a68725c09dc'
down_revision = '37ddb4c43df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biography', sa.VARCHAR(length=355), nullable=False))
    # ### end Alembic commands ###
