"""empty message

Revision ID: 97802a401c26
Revises: 6c5cc7cf888c
Create Date: 2023-01-23 09:32:09.278927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97802a401c26'
down_revision = '6c5cc7cf888c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('brief', sa.String(length=150), nullable=False))
    op.add_column('stories', sa.Column('estimated_read', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'estimated_read')
    op.drop_column('stories', 'brief')
    # ### end Alembic commands ###